### ISSUE TITLE
Should I reverse CS signal for BIOS chip with a SOP8 test clip?

### ISSUE THREAD

**Issue by fenfenS** [zaphoxx/pico-tpmsniffer-spi#6]
Connecting the SPI bus through a SOP8 test clip and the BIOS chip.
Should I change this line [spi_sniffer.pio#L11](https://github.com/zaphoxx/pico-tpmsniffer-spi/blob/d69f67955bfd26f57d53fd07d67c6f88b20065c3/spi_sniffer.pio#L11) to `wait 0 pin 3`?
Or I just mess it around?

**Comment by fenfenS** [comment]
nope, I did mess it around. when CS low , the communication for the device is enabled usually.

**Comment by zaphoxx** [comment]
Hi, CS should be set to active High to capture the TPM communication instead of the communication with the BIOS chip if you are connected to the BIOS Chip. So the command makes sure CS is active high before capturing the bits. In other words it should be´´wait 1 pin 3´´. 

If you have access to the actual TPM CS line then you might want to set it the other way round but need to check if the logic of the code still works for that case.

**Comment by zaphoxx** [comment]
if you have any issues, the following code is a slight variation of this one and might work slightly better
https://github.com/zaphoxx/pico-tpmsniffer/blob/patch-spi/spi_sniffer.pio

**Comment by fenfenS** [comment]
Understood, I did use the SOP8 test clip, and connected it to BIOS chip (TPM in the same SPI bus).
So I used the tpm_sniffer_spi.uf2 from the repo directly, thank you so much for your explanation.

**Comment by zaphoxx** [comment]
> Understood, I did use the SOP8 test clip, and connected it to BIOS chip (TPM in the same SPI bus).
> So I used the tpm_sniffer_spi.uf2 from the repo directly, thank you so much for your explanation.

Did. it work out ok? Or did you encounter any issues? Which laptop did you try?
Best

**Comment by fenfenS** [comment]
Thinkpad S2 gen6( ST33TPHF2XSPI SPI/TPM 2.0), I have sent the pico to my friend who got his disk locked.
When I have new updates, I 'd like to share them :)
